export default [
  {
    id: 0,
    name: "Alice",
    recentMessage: "Hey, how are you?",
    onlineStatus: true,
    recentMessageTime: "10:30",
    numberOfNewMessages: 2,
    gender: "girl",
  },
  {
    id: 1,
    name: "Bob",
    recentMessage: "I'm doing well, thanks!",
    onlineStatus: false,
    recentMessageTime: "15:20",
    numberOfNewMessages: 0,
    gender: "boy",
  },
  {
    id: 2,
    name: "Charlie",
    recentMessage: "Can we meet tomorrow?",
    onlineStatus: true,
    recentMessageTime: "09:45",
    numberOfNewMessages: 1,
    gender: "boy",
  },
  {
    id: 3,
    name: "Eva",
    recentMessage: "How's your day going?",
    onlineStatus: true,
    recentMessageTime: "11:15",
    numberOfNewMessages: 3,
    gender: "girl",
  },
  {
    id: 4,
    name: "David",
    recentMessage: "See you at the party tonight!",
    onlineStatus: true,
    recentMessageTime: "18:40",
    numberOfNewMessages: 0,
    gender: "boy",
  },
  {
    id: 5,
    name: "Emma",
    recentMessage: "I'll be there soon.",
    onlineStatus: false,
    recentMessageTime: "17:55",
    numberOfNewMessages: 0,
    gender: "girl",
  },
  {
    id: 6,
    name: "Frank",
    recentMessage: "Got the project files ready?",
    onlineStatus: true,
    recentMessageTime: "09:00",
    numberOfNewMessages: 2,
    gender: "boy",
  },
];
